services:
  - type: web
    name: chaskiq
    env: ruby
    buildCommand: bundle install && yarn install && bundle exec rails assets:precompile
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: HOST
        sync: false
      - key: WS
        sync: false
      - key: ASSET_HOST
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        generateValue: true
    healthCheckPath: /

databases:
  - name: chaskiq-db
    databaseName: chaskiq_production
    user: chaskiq

redis:
  - name: chaskiq-redis


